### ISSUE TITLE
Route order shouldn't be based on alphabetical controller name order

### ISSUE THREAD

**Issue by sattes-faction** [sensiolabs/SensioFrameworkExtraBundle#227] opened 2013-07-04 08:13 UTC
I'm having a Custom route loader that is looking for registered bundles and automatically registers their routes (following the [guidelines in the cookbook](http://symfony.com/doc/current/cookbook/routing/custom_route_loader.html)). Here's a short snippet:

    [...]
    foreach ($bundles as $bundle) {    
        $resource = '@'.$bundle.'/Controller';
        $type = "annotation";

        $importedRoutes = $this->import($resource, $type);
        $collection->addCollection($importedRoutes);
    }
    [...]

The problem I'm facing is that when using the Controller folder annotation and not specifying the controllers explicetly, the routes are loaded as defined in the alphabetical order of their controller names. 
The routes of `FileController` for example always are defined after the routes in `DefaultController`.

**Comment by javiereguiluz** [comment] 2015-07-17 18:53
This is a well-know limitation. In the past there were some proposals to define some kind of order or priority, but none was implemented. I'm proposing to close this issue as "won't fix" because solving this would require a lot of work and because, as explained bt @sattes-faction, there is already an alternative solution: define the controllers explicitly to control their order instead of loading the entire bundle.

**Comment by Tobion** [comment] 2016-06-06 23:40
Duplicate of #320 and symfony/symfony#18415 etc.

**Closed** 2016-06-07 05:24 UTC
