### ISSUE TITLE
There is no `@Entity` annotation in the latest release

### ISSUE THREAD

**Issue by Invis1ble** [sensiolabs/SensioFrameworkExtraBundle#444] opened 2016-10-30 08:33 UTC
[Docs says about `@Entity` annotation](https://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/converters.html):

> Use the special `@Entity` annotation with an expr option to fetch the object by calling a method on your repository.

but I cant't find it in the latest `sensio/framework-extra-bundle` release.

I'm using `v3.0.16`.

**Comment by xabbuh** [comment] 2016-10-30 08:52
The issue is that the URL you linked to is in fact the generated documentation for the upcoming 4.0 release while the version switcher indicates 3.0 (you can see the differences by explicitly choosing 3.0 there).

@javiereguiluz Any idea what's going wrong in the doc generation process?

**Comment by Aerendir** [comment] 2016-11-02 16:36
So this is a feature only of the 4.0 version? Because I'm having the same exact problem: no Entity annotation.

**Comment by iltar** [comment] 2016-11-02 17:28
@xabbuh it seems like the master is loaded as current, while the dropdown specifies 3.0. If you switch to the master and then to 3.0 you get the right one.

**Comment by xabbuh** [comment] 2016-11-02 20:45
@iltar Indeed, that's what I meant with "you can see the differences by explicitly choosing 3.0 there". Though I have no possibility to fix this and we need @javiereguiluz' help.

**Comment by javiereguiluz** [comment] 2016-12-27 15:55
This error was finally fixed ... so we can close this issue as "fixed". Thanks.

**Closed** 2016-12-27 20:35 UTC
