### ISSUE TITLE
[DX] @Route Priority

### ISSUE THREAD

**Issue by weaverryan** [sensiolabs/SensioFrameworkExtraBundle#320] opened 2014-08-21 18:24 UTC
This has been proposed before #79, but I have a different reason for why it should be included.

Suppose I import annotations from the entire controller directory:

```yml
app_routes:
    resource: "@AppBundle/Controller"
    type:     annotation
```

Once I do this, I can't control the order in which the Controller files themselves are parsed. If I need FooController.php to be parsed before DefaultController.php (because *one* route in FooController.php needs to be before a route in DefaultController.php), then I can't do this. I can of course start importing the controller classes directly, but if I have 10 files, I need to take my one simple import and change it to be 10 individual imports.

So, I'd like to see a `priority` option on routes, for the use-case of needing one route to be higher or lower *within the routes loaded by a single import*.

I've tagged this with DX, because if you choose to use route annotations, then this really takes away the "shine" of them :).

Thoughts?

**Comment by Tobion** [comment] 2016-06-06 23:41
Duplicate of #227 and symfony/symfony#18415 etc.

**Closed** 2016-06-07 05:24 UTC
