### ISSUE TITLE
Custom ParamConverter bug (cant' get ride of Doctrine converter)

### ISSUE THREAD

**Issue by skornev** [sensiolabs/SensioFrameworkExtraBundle#483] opened 2017-08-01 18:27 UTC
I cant' find the way to get ride of Doctrine converter.
Documentation says:

If an explicit converter choice was made with @paramconverter(converter="name") the converter with the given name is chosen.
But it still calls both custom and doctrine converter.

**Comment by jakzal** [comment] 2017-08-02 08:20
Could you show us the method signature and how you configured your param converter(s)?

**Comment by jakzal** [comment] 2017-08-02 08:33
Possibly a duplicate of #472

**Comment by skornev** [comment] 2017-08-02 12:40
`@ParamConverter(name="id", converter="custom_converter", class="AppBundle\Entity\MyEntity")
`services ()

```
   custom_converter:
        class: AppBundle\Request\ParamConverter\CustomConverter
        tags:
            - { name: request.param_converter, priority: -2, converter: custom_converter }
```

Set priority="false" does not help either.

**Comment by jakzal** [comment] 2017-08-02 12:46
What's the controller method signature (list of arguments)?

**Comment by skornev** [comment] 2017-08-02 15:45
```
    /**
     *  @Route("/{id}/save/", name="admin_save")
     * @ParamConverter(name="id", converter="custom_converter", class="AppBundle\Entity\MyEntity")    
     * @param MyEntity $id
   **/
 public function someAction(MyEntity $id)
 {

 }
```

This also does not work


    /**
     *  @Route("/{another_name}/save/", name="admin_save")
     * @ParamConverter(name="another_name", converter="custom_converter", class="AppBundle\Entity\MyEntity")    
     * @param MyEntity $id
   **/
 public function someAction(MyEntity $another_name)
 {

 }

**Comment by fabpot** [comment] 2017-09-15 06:18
see #511

**Comment by fabpot** [comment] 2017-09-15 06:39
I've just tested and if you have a named converter that supports Doctrine entities, it is always applied instead of the Doctrine one.

Having 2 converter running for the same argument is not possible.

**Closed by fabpot** 2017-09-15 06:39 UTC
Labels: Doctrine converter
