### ISSUE TITLE
any way to configure global optional _locale?

### ISSUE THREAD

**Issue by jurchiks** [sensiolabs/SensioFrameworkExtraBundle#397] opened 2016-01-29 15:04 UTC
Currently, all actions in all my controllers are annotated like this:
```
    /**
     * @Route("/")
     * @Route("/{_locale}/", name="homepage", requirements={"_locale"="%allowed_locales%"})
     */
    public function indexAction(Request $request)
...
    /**
     * @Route("/vip/")
     * @Route("/{_locale}/vip/", name="vip", requirements={"_locale"="%allowed_locales%"})
     */
    public function vipAction(Request $request)
...
    /**
     * @Route("/hotel/")
     * @Route("/{_locale}/hotel/", name="hotel", requirements={"_locale"="%allowed_locales%"})
     */
    public function hotelAction(Request $request)
...
```
Obviously, this is not DRY. I have tried searching for a solution, including creating a stackoverflow question, but have not found a fix yet. Is there any way to put this optional _locale in a config somewhere to avoid copying it on every action?

This really feels like it should be a built-in feature.

**Comment by Ener-Getick** [comment] 2016-01-31 20:42
You can load your controllers twice:
```yaml
blog_home:
    path:     /
    defaults: { _controller: SensioBlogBundle:Post:index }

blog_home_localized:
    path:     /{_locale}/
    defaults: { _controller: SensioBlogBundle:Post:index }

**Comment by jurchiks** [comment] 2016-01-31 20:58
Is that the exact syntax for Symfony 3 routing.yml? Because currently all there is in it is:
```
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
```
And even if so, that syntax looks like I would still have to duplicate it for every controller.

**Comment by Ener-Getick** [comment] 2016-01-31 21:03
That was just an example, you can for example move your routes from ``routing.yml`` to ``localized_routing.yml`` and update ``routing.yml``:
```yml
_routing:
    resource: localized_routing.yml

_localized_routing:
    path: /{_locale}/
    resource: localized_routing.yml

**Comment by jurchiks** [comment] 2016-01-31 21:03
I tried doing this:
```
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
app_localized:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix: '/{_locale}'
    requirements:
        _locale: '%allowed_locales%'
```
But it doesn't even find the index page: `No route found for "GET /"`.

**Comment by jurchiks** [comment] 2016-01-31 21:04
Ok, I'll try that.

**Comment by Ener-Getick** [comment] 2016-01-31 21:05
oops sorry that's ``prefix`` not ``path``

**Comment by Ener-Getick** [comment] 2016-01-31 21:06
That's weird your code should work... 
Did you update your controller at the same time?

**Comment by jurchiks** [comment] 2016-01-31 21:07
Yeah, I deleted all the localized Route annotations.

**Comment by Ener-Getick** [comment] 2016-01-31 21:10
Can you try to run ``bin/console debug:router``?

**Comment by jurchiks** [comment] 2016-01-31 21:10
Ok, still doesn't work.

What I have:
DefaultController.php:
```
/**
     * @Route("/", name="home")
     */
    public function indexAction()
    {
        return $this->render('default/index.html.twig');
    }
```

routing.yml:
```
_routing:
    resource: routing_localized.yml
_routing_localized:
    resource: routing_localized.yml
    prefix: /{_locale}
    requirements:
        _locale: %allowed_locales%
```

routing_localized.yml:
```
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
```

**Comment by jurchiks** [comment] 2016-01-31 21:11
Running debug:router, I get this output:
```
 -------------------------- -------- -------- ------ -------------------------------------
  Name                       Method   Scheme   Host   Path
 -------------------------- -------- -------- ------ -------------------------------------
  _wdt                       ANY      ANY      ANY    /_wdt/{token}
  _profiler_home             ANY      ANY      ANY    /_profiler/
  _profiler_search           ANY      ANY      ANY    /_profiler/search
  _profiler_search_bar       ANY      ANY      ANY    /_profiler/search_bar
  _profiler_info             ANY      ANY      ANY    /_profiler/info/{about}
  _profiler_phpinfo          ANY      ANY      ANY    /_profiler/phpinfo
  _profiler_search_results   ANY      ANY      ANY    /_profiler/{token}/search/results
  _profiler                  ANY      ANY      ANY    /_profiler/{token}
  _profiler_router           ANY      ANY      ANY    /_profiler/{token}/router
  _profiler_exception        ANY      ANY      ANY    /_profiler/{token}/exception
  _profiler_exception_css    ANY      ANY      ANY    /_profiler/{token}/exception.css
  _twig_error_test           ANY      ANY      ANY    /_error/{code}.{_format}
  home                       ANY      ANY      ANY    /{_locale}/
  casino                     ANY      ANY      ANY    /{_locale}/casino/
  restaurant                 ANY      ANY      ANY    /{_locale}/restaurant/
  slot_machines              ANY      ANY      ANY    /{_locale}/slot-machines/
  vip                        ANY      ANY      ANY    /{_locale}/vip/
  hotel                      ANY      ANY      ANY    /{_locale}/hotel/
  slider_list                ANY      ANY      ANY    /{_locale}/slider/list/
  slider_add                 ANY      ANY      ANY    /{_locale}/slider/add/
  slider_update              ANY      ANY      ANY    /{_locale}/slider/update/{id}
  slider_update_positions    ANY      ANY      ANY    /{_locale}/slider/update-positions/
  slider_delete              ANY      ANY      ANY    /{_locale}/slider/delete/{id}
 -------------------------- -------- -------- ------ -------------------------------------
```

**Comment by jurchiks** [comment] 2016-01-31 21:15
I also tried making a copy of "routing_localized.yml", naming it "routing_non_localized.yml", and pointing "_routing:resource:" to non_localized, but that didn't work either.

**Comment by jurchiks** [comment] 2016-01-31 21:17
It looks to me that Symfony simply overwrites the non-localized routes with the localized ones because if I comment out the _routing_localized: block in routing.yml, it outputs the same thing but without the _locale prefix.

**Comment by Ener-Getick** [comment] 2016-01-31 21:20
Yeah I think this is because they have the same name so IMO the only solution you have is to add your prefix for each import.

**Comment by jurchiks** [comment] 2016-01-31 21:21
But all my routing is in annotations and routing.yml only contains the general loader. There is no "each import" to prefix.

**Comment by jurchiks** [comment] 2016-01-31 21:21
Was this working in Symfony 2? Did they break BC in v3?

**Comment by jurchiks** [comment] 2016-01-31 21:26
Well, good thing I can at least move the _locale requirement to routing.yml:
```
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    requirements:
        _locale: %allowed_locales%
```
and have the route annotations not contain it:
```
    /**
     * @Route("/", name="home")
     * @Route("/{_locale}/", name="home_lang")
     */
    public function indexAction()
    {
        return $this->render('default/index.html.twig');
    }
```
This really feels wrong though, but it's more DRY than nothing, I guess...

**Comment by Ener-Getick** [comment] 2016-01-31 21:29
No the router works globally the same way.

The problem is caused by the route names which are identical when you import twice a controller so the first create is overwritten. Unfortunately, I think there is no solution for you actually.
I'll open a ticket on symfony to see if we can add a feature allowing to prefix route names.

**Comment by jurchiks** [comment] 2016-01-31 21:30
Oh wait, no, something doesn't work with this, Twig route generation with different locales now doesn't add the _locale prefix where it should... I guess I'll just have to stick to duplicate annotations for now.

**Comment by jurchiks** [comment] 2016-01-31 21:32
Basically the problem is in the fact that you cannot just specify an optional route parameter.
If I could just write `@Route('/{_locale?}/foo/', name="foo")` and have the _locale requirements defined globally, that would be all that I need.
I'm 100% sure that many other people need exactly this same thing.

**Comment by Ener-Getick** [comment] 2016-01-31 21:37
Unfortunately, I don't think this is doable easily with the current implementation...

**Comment by jurchiks** [comment] 2016-01-31 21:38
Yeah, that's what happens when a tool tries to be everything for everyone... Too much complexity.

**Comment by Ener-Getick** [comment] 2016-01-31 21:44
I'll create you a ``gist`` containing a more complex solution but still easier than having so many routes declaration ;-)

**Comment by jurchiks** [comment] 2016-01-31 21:45
Ok, thanks!

**Comment by Ener-Getick** [comment] 2016-01-31 22:04
[this](https://gist.github.com/Ener-Getick/3b9400105ee2ad9429e1) should work

**Comment by jurchiks** [comment] 2016-01-31 22:56
Unfortunately it fails to load `_routing.resource`.

**Comment by jurchiks** [comment] 2016-01-31 23:14
Fixed it, posted the fix on gist.

**Comment by Ener-Getick** [comment] 2016-02-01 06:10
No I don't get any notifications from gist. 
I updated the gist with your fix ☺

I guess this issue can now be closed?

**Comment by jurchiks** [comment] 2016-02-01 12:53
Yeeeeah, well, it would be nice if something like this would be easier to implement. Like I said, a globally defined optional prefix "/{_locale}" would be great, but by that I don't mean two routes for one action (with and without prefix), but rather just an optional parameter for the same route.

**Comment by Ener-Getick** [comment] 2016-02-01 14:08
Yeah but that's technically too complicated. 
Be aware that this routing loader might provoke priority bugs if a route begins with something similar to a locale.

**Comment by jurchiks** [comment] 2016-02-01 15:13
Well, I might try to make it sometime in the future.

Are you sure? I have the locale restricted to "en|ru|tk". Doesn't symfony generate a regex for this? If so, then it shouldn't be a problem, the regex should look like "/(en|ru|tk)/foo/bar/".

**Comment by Ener-Getick** [comment] 2016-02-01 15:22
Yeah it's just that the localized routes are added after normal one so in case you have something like this psycho code :
```yml
bar:
    path: /{bar}
    type: localized
foo:
    path: /en/foo
    type: localized
```

foo should never be used normally but in case you request ``/en/foo`` it will match ``foo`` instead of ``bar`` if you think you will use this kind of this, I can create a fix.

**Comment by jurchiks** [comment] 2016-02-01 15:29
Naaa, I don't think I'll have that. But if I do, I'll post here.

**Comment by Ener-Getick** [comment] 2016-02-01 15:33
You're welcome BTW it would be cool if this was integrated in symfony but there were already pr trying to introduce such feature and they were rejected :-/
But there weren't any use cases described so I think we can try to open them again.

**Comment by jurchiks** [comment] 2016-02-01 15:54
Weird, this is such a common use case...
By the way, I also made this Twig extension for this exact use case in templates: https://gist.github.com/jurchiks/3b4e1bd249d7e8c1b60e

I'll have to check those PRs out.

**Comment by jurchiks** [comment] 2016-02-03 17:59
Could you maybe post a link to any of those PRs? I tried looking for closed PRs by "locale", "route", "prefix" and "parameter", but couldn't find anything related.

**Comment by Ener-Getick** [comment] 2016-02-03 19:44
I found that one https://github.com/symfony/symfony/pull/11770

**Comment by jurchiks** [comment] 2016-02-04 00:43
Well, that one is for NAME prefix...
I guess I'll have to check out their source code and try to come up with something. After all, they clearly want the feature for all possible routing mechanisms if they're going to accept it.

**Comment by fabpot** [comment] 2016-09-21 22:30
Closing this one as there is nothing to do here, it's more for Symfony I guess.

**Closed by fabpot** 2016-09-21 22:30 UTC
